[package]
name = "subject_decoding"
type = "bin"
authors = [""]

[dependencies]
zkemail = { tag = "v.1.0.1-beta.5", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
zkregex = { tag = "2.2.0", git = "https://github.com/zkemail/zk-regex", directory = "noir" }
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
sha256 = { git = "https://github.com/noir-lang/sha256", tag = "v0.1.2" }
noir_base64 = { path = "/Users/johnson/nargo/github.com/noir-lang/noir_base64/v0.4.0" }
lib = { path = "../lib" }
